[build]
  command = "yarn install --frozen-lockfile && yarn build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  # Se algum pacote reclamar de engines, descomente:
  # YARN_IGNORE_ENGINES = "true"
