[build]
  base    = "site"                                   # entra em /site
  command = "yarn install --frozen-lockfile && yarn build"
  publish = "dist"                                   # publica /site/dist

[build.environment]
  NODE_VERSION = "16.20.2"
  YARN_IGNORE_ENGINES = "true"
